### ISSUE TITLE
microblog.pub next steps???

### ISSUE THREAD

**Issue by nigini** [778a0a/microblog#1]
Hey there. (Sorry to use your project's issue to communicate... I did not find a more proper way to contact you.)

I saw you started playing with MicroBlog.pub recently, as I did myself. However, I discovered that the original author hadn't been responsive, and I got the idea to join forces to keep the project moving. If you'd like to exchange ideas and code: https://github.com/orgs/microblog-pub/discussions

**Comment by 778a0a** [comment]
Thanks for reaching out!
It's very interesting.
I'll take a look at the link.
